/* SPDX-License-Identifier: GPL-3.0-only
 * Verifies the pinned Pulseboard SDK v3 artifact (observatory/pulseboard.js) against observatory.lock.json.
 * Built from Chris0Jeky/Pulseboard observatory/adapters/build-sdk.mjs; see observatory/README.md.
 * Product-specific assertions about the built site live in observatory/check.local.mjs. */
import { createHash } from 'node:crypto';
import { lstatSync, readFileSync, realpathSync } from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath, pathToFileURL } from 'node:url';

const SOURCE = 'Chris0Jeky/Pulseboard:observatory';
const SDK_VERSION = '3.1.0';
const COLLECTOR = 'https://pulseboard-observatory.commit-atlas.workers.dev';
const ORIGIN = 'https://alibi-after-hours-preview.commit-atlas.workers.dev';
const HEADER = /^\/\* SPDX-License-Identifier: GPL-3\.0-only\n \* pulseboard-sdk (\S+) for ([a-z0-9-]+)\. Generated by observatory\/adapters\/build-sdk\.mjs; do not edit\.\n \* sha256 of the body below: ([0-9a-f]{64}) \*\/\n/;
const here = path.dirname(fileURLToPath(import.meta.url));
const root = realpathSync(path.resolve(here, '..'));
const sha256 = (value) => createHash('sha256').update(value).digest('hex');
const normalise = (value) => value.replaceAll('\r\n', '\n');
const fail = (message) => {
  throw new Error(message);
};
function ownedFile(relative, label) {
  if (typeof relative !== 'string' || path.isAbsolute(relative) || relative.split(/[\\/]/).includes('..'))
    fail(label + ' path leaves repository');
  const full = path.resolve(root, relative);
  if (full === root || !full.startsWith(root + path.sep)) fail(label + ' path leaves repository');
  const stat = lstatSync(full, { throwIfNoEntry: false });
  if (!stat || !stat.isFile() || stat.isSymbolicLink())
    fail(label + ' is missing, not a file, or a symlink: ' + relative);
  const parent = realpathSync(path.dirname(full));
  if (parent !== root && !parent.startsWith(root + path.sep)) fail(label + ' parent leaves repository: ' + relative);
  return full;
}

// 1. The lock pins exactly one SDK v3 artifact for alibi.
const lock = JSON.parse(readFileSync(ownedFile('observatory.lock.json', 'Observatory lock'), 'utf8'));
if (lock.source !== SOURCE) fail('Unexpected Observatory lock source');
if (lock.sdk !== SDK_VERSION) fail('The lock must declare "sdk": "' + SDK_VERSION + '"');
if (!lock.installs || Object.getPrototypeOf(lock.installs) !== Object.prototype) fail('Unsupported Observatory lock shape');
const entries = Object.entries(lock.installs);
if (entries.length !== 1) fail('Alibi must have exactly one installed Pulseboard artifact');
const [target, owned] = entries[0];
if (owned?.project !== 'alibi' || owned.sdk !== SDK_VERSION || !/^[a-f0-9]{64}$/.test(owned.sha256 ?? ''))
  fail('Invalid lock entry for ' + target);

// 2. The bytes match the lock and are an unedited builder artifact for this SDK and project.
const content = normalise(readFileSync(ownedFile(target, 'Pulseboard artifact'), 'utf8'));
const actual = sha256(content);
if (actual !== owned.sha256) fail('Integrity mismatch for ' + target + ': expected ' + owned.sha256 + ', got ' + actual);
const header = HEADER.exec(content);
if (!header) fail('The artifact header does not name a pulseboard-sdk build');
if (header[1] !== SDK_VERSION || header[2] !== 'alibi') fail('The artifact header must name pulseboard-sdk ' + SDK_VERSION + ' for alibi');
if (sha256(content.slice(header[0].length)) !== header[3]) fail('The artifact body differs from its header hash (edited by hand)');
const leaked = content.split('\n').find((line) => /^(?:import|export)\b/.test(line));
if (leaked) fail('Generated artifact contains a module statement: ' + leaked.slice(0, 60));
if (/MAX_BYTES|MAX_BATCH/.test(content)) fail('Generated artifact contains server-only constants');

// 3. The embedded client contract: this project, its public origin, the one collector, and this release.
const configLines = content.split('\n').filter((line) => line.startsWith('const config = '));
if (configLines.length !== 1) fail('The artifact has no unique generated client configuration');
const config = JSON.parse(/^const config = (\{.*\});$/.exec(configLines[0])?.[1] ?? 'null');
if (config?.id !== 'alibi' || config.origin !== ORIGIN) fail('The artifact is not configured for the Alibi origin');
if (config.collector !== COLLECTOR) fail('The artifact collector must be ' + COLLECTOR);
const releases = config.project?.releases;
if (!Array.isArray(releases)) fail('The artifact has no closed release contract');
const manifest = JSON.parse(readFileSync(ownedFile('package.json', 'Alibi package manifest'), 'utf8'));
if (manifest.name !== 'alibi-puzzle-club' || !/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(manifest.version ?? ''))
  fail('The alibi artifact requires the Alibi package manifest with a stable x.y.z version');
if (config.release !== manifest.version || !releases.includes(manifest.version))
  fail(
    'Alibi ' + manifest.version + ' is not the release built into ' + target + ' (' + config.release + '; registered: ' +
      releases.join(', ') + '). Register the release in Pulseboard, then rebuild the artifact.',
  );
const catalogue = JSON.parse(readFileSync(ownedFile('content/releases.json', 'Alibi release catalogue'), 'utf8'));
const matching = Array.isArray(catalogue) ? catalogue.filter((release) => release?.version === manifest.version) : [];
if (matching.length !== 1 || matching[0].tag !== 'v' + manifest.version)
  fail('Alibi content/releases.json must contain exactly one matching v' + manifest.version + ' record');
for (const route of ['home', 'puzzle', 'castle', 'quiet-wing', 'other'])
  if (!config.project.routes?.includes(route)) fail('The artifact is missing the registered route ' + route);
for (const event of ['page.view', 'puzzle.started', 'puzzle.completed', 'puzzle.failed', 'hint.requested'])
  if (!config.project.events?.includes(event)) fail('The artifact is missing the registered count ' + event);

// 4. Loaded in a fake window it defines a frozen window.Pulseboard without throwing, and makes no network
// call before its notice mounts; off the registered origin or under automation it stays inert.
function fakeWindow({ origin = ORIGIN, webdriver = false } = {}) {
  const calls = [];
  const listeners = {};
  const node = (tag) => ({
    tag,
    children: [],
    style: {},
    attributes: {},
    append(...nodes) {
      this.children.push(...nodes);
    },
    prepend(...nodes) {
      this.children.unshift(...nodes);
    },
    setAttribute(name, value) {
      this.attributes[name] = String(value);
    },
    addEventListener() {},
    remove() {},
  });
  const body = node('body');
  const document = {
    readyState: 'loading',
    body,
    referrer: '',
    visibilityState: 'visible',
    documentElement: { scrollHeight: 1000, clientHeight: 800, scrollTop: 0 },
    createElement: node,
    querySelector: () => null,
    addEventListener(type, fn) {
      (listeners[type] ||= []).push(fn);
    },
    removeEventListener() {},
  };
  const store = () => {
    const map = new Map();
    return {
      getItem: (key) => (map.has(key) ? map.get(key) : null),
      setItem: (key, value) => map.set(key, String(value)),
      removeItem: (key) => map.delete(key),
    };
  };
  const context = {
    document,
    navigator: { webdriver },
    location: { origin, protocol: new URL(origin).protocol, href: origin + '/', search: '' },
    localStorage: store(),
    sessionStorage: store(),
    innerWidth: 390,
    innerHeight: 800,
    AbortController,
    TextEncoder,
    URL,
    crypto: { randomUUID: () => '00000000-0000-4000-8000-000000000001' },
    performance: { now: () => 0, getEntriesByType: () => [] },
    matchMedia: () => ({ matches: false }),
    setTimeout: () => 1,
    clearTimeout() {},
    addEventListener() {},
    removeEventListener() {},
    fetch(url) {
      calls.push(url);
      return new Promise(() => {});
    },
  };
  context.globalThis = context;
  vm.createContext(context);
  return { context, calls, body, ready: () => (listeners.DOMContentLoaded || []).forEach((fn) => fn()) };
}
const live = fakeWindow();
vm.runInContext(content, live.context, { filename: target });
const api = live.context.Pulseboard;
if (!api || api.version !== SDK_VERSION || !Object.isFrozen(api)) fail('The artifact did not define a frozen window.Pulseboard ' + SDK_VERSION);
if (live.calls.length) fail('The artifact made a network call before its notice mounted');
live.ready();
if (!live.body.children.length) fail('The artifact did not mount its notice on DOMContentLoaded');
for (const options of [{ origin: 'https://example.com' }, { origin: 'http://127.0.0.1:8787' }, { webdriver: true }]) {
  const inert = fakeWindow(options);
  vm.runInContext(content, inert.context, { filename: target });
  inert.ready();
  if (!inert.context.Pulseboard || inert.context.Pulseboard.count('page.view') !== false || inert.calls.length || inert.body.children.length)
    fail('The artifact must stay inert for ' + JSON.stringify(options));
}

const report = {
  source: SOURCE,
  sdk: SDK_VERSION,
  targets: [target],
  alibi: { packageVersion: manifest.version, catalogueTag: matching[0].tag, registeredReleases: releases, artifactSha256: actual },
};
const localPath = path.join(here, 'check.local.mjs');
const localStat = lstatSync(localPath, { throwIfNoEntry: false });
if (localStat) {
  if (!localStat.isFile() || localStat.isSymbolicLink()) fail('observatory/check.local.mjs must be a regular file');
  const local = await import(pathToFileURL(localPath).href);
  const check = local.default ?? local.check;
  if (typeof check !== 'function') fail('observatory/check.local.mjs must export a default function or check()');
  await check(Object.freeze({ root, source: SOURCE, lock: Object.freeze(lock), target, content, config }));
}
console.log(JSON.stringify(report));
