"""Real local WebGL, fallback and resource lifecycle; no physical GPU certification."""
from pathlib import Path
import json, os, shutil
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results/quiet-wing';OUT.mkdir(parents=True,exist_ok=True)
checks=[];errors=[];measurements={}
def check(v,label):
    assert v,label
    checks.append(label);print('PASS',label,flush=True)
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium'),headless=True,args=['--enable-unsafe-swiftshader'])
    ctx=browser.new_context(viewport={'width':1280,'height':900})
    page=ctx.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
    base=os.environ.get('ALIBI_URL','http://127.0.0.1:8787/')
    page.goto(base+'#/quiet/realm');page.wait_for_function('()=>window.QWApp?.renderer?.w')
    check(page.evaluate('QWApp.renderer.mode')=='webgl','Actual WebGL renderer initializes')
    check(page.evaluate('QWApp.renderer.objects.length')==2,'Town and water render in two geometry batches')
    page.evaluate('QWApp.renderer.setMotion(false)')
    measurements['defaultScene']=page.evaluate('({submitMs:QWApp.renderer.lastMs,triangles:QWApp.renderer.gpu.info.render.triangles,drawCalls:QWApp.renderer.gpu.info.render.calls})')
    page.evaluate('QWApp.renderer.setMotion(true)')
    check(page.evaluate('QWApp.renderer.frame > 0'),'Motion schedules while visible')
    page.evaluate("Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))")
    check(page.evaluate('QWApp.renderer.frame')==0,'Simulated hidden document stops all animation frames')
    page.evaluate("delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))")
    page.emulate_media(reduced_motion='reduce');page.evaluate('QWApp.renderer.setMotion(true)')
    check(page.evaluate('QWApp.renderer.frame')==0,'Reduced motion disables water animation')
    page.emulate_media(reduced_motion='no-preference')
    page.evaluate('window.savedRender=QWApp.renderer.render;QWApp.renderer.render=function(){this.lastMs=60};QWApp.renderer.setMotion(true)')
    page.wait_for_function('()=>QWApp.renderer.motionPaused===true')
    check(page.evaluate('QWApp.renderer.frame')==0,'Repeated slow-frame fixture pauses ambient motion')
    page.evaluate('QWApp.renderer.render=window.savedRender;QWApp.renderer.setMotion(false)')
    target=page.evaluate('()=>{let r=QWApp.renderer;let i=r.scene.tiles.findIndex(t=>!t.items.length&&t.ground!=="water");return {index:i,point:r.project(i%r.scene.size+.5,Math.floor(i/r.scene.size)+.5,r.scene.tiles[i].height*.43+.01)}}')
    check(page.evaluate('(p)=>QWApp.renderer.pick(...p)',target['point'])==target['index'],'Ray picking agrees with the displayed projection')
    page.locator('[data-view="plan"]').click()
    page.screenshot(path=str(OUT/'city-gpu-plan.png'),full_page=True)
    page.evaluate("window.loss=QWApp.renderer.gpu.getContext().getExtension('WEBGL_lose_context');loss.loseContext()")
    page.wait_for_function('()=>QWApp.renderer.mode==="canvas"')
    check(page.evaluate('QWApp.renderer.frame')==0,'Actual context loss switches to a non-animated fallback')
    page.locator('.plot-controls summary').click();page.locator('[data-category="Tools"]').click();page.locator('[data-tool="raise"]').click()
    before=page.evaluate('QWApp.state.scene.tiles[0].height')
    page.locator('#plot-apply').click();check(page.evaluate('QWApp.state.scene.tiles[0].height')==before+1,'Editing remains usable after context loss')
    page.evaluate('loss.restoreContext()');page.wait_for_function('()=>QWApp.renderer.mode==="webgl"')
    check(page.evaluate('QWApp.state.scene.tiles[0].height')==before+1,'Restored WebGL retains the fallback edit')
    page.evaluate('window.oldRenderer=QWApp.renderer;location.hash="/quiet/pets"');page.wait_for_function('()=>QWApp.route==="pets"')
    check(page.evaluate('oldRenderer.disposed&&oldRenderer.frame===0&&oldRenderer.objects.length===0'),'Leaving realm disposes geometry, context and animation')
    fallback=browser.new_context(viewport={'width':390,'height':850})
    fallback.add_init_script("const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.startsWith('webgl')?null:original.call(this,type,...args)}")
    other=fallback.new_page();other.on('pageerror',lambda e:errors.append(str(e)))
    other.goto(base+'#/quiet/realm');other.wait_for_function('()=>window.QWApp?.renderer?.w')
    check(other.evaluate('QWApp.renderer.mode')=='canvas','Browser without WebGL opens the same editable town')
    check(other.evaluate('QWApp.renderer.mesh.length')==196,'Fallback retains all original plots')
    other.screenshot(path=str(OUT/'city-canvas-fallback.png'),full_page=True)
    check(not errors,'No uncaught errors through GPU loss and fallback')
    (OUT/'city-gpu-results.json').write_text(json.dumps({'checks':checks,'errors':errors,'measurements':measurements,'scope':'Headless local Chromium; software/GPU submission measurements are not phone frame rates'},indent=2))
    browser.close()
