"""Real-control discovery and historical changelog acceptance; simulated viewports."""
import json, os
from pathlib import Path
from official_fixture import OFFICIAL_COUNT, official_puzzles
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[1]
RELEASES=json.loads((ROOT/'content/releases.json').read_text(encoding='utf-8'))
OUT=Path(os.environ.get('ALIBI_RESULTS',str(ROOT/'test-results/discovery'))); OUT.mkdir(parents=True,exist_ok=True)
URL=os.environ.get('ALIBI_URL','http://127.0.0.1:8787').rstrip('/')
checks=[]
BINARY_COUNT=sum(puzzle.get('type')=='binary' for puzzle in official_puzzles())
(OUT/'results.json').write_text(json.dumps({'passed':False,'status':'running'}))
def check(value,label):
    assert value,label
    checks.append(label)
with sync_playwright() as pw:
    browser=pw.chromium.launch()
    for width in [390,1440]:
        context=browser.new_context(viewport={'width':width,'height':900}, reduced_motion='reduce')
        page=context.new_page(); errors=[]
        page.on('pageerror',lambda e: errors.append(str(e)))
        page.goto(URL+'/#/home')
        expect(page.locator('.club-news .collection-card')).to_have_count(4)
        page.locator('.club-news').scroll_into_view_if_needed()
        page.wait_for_function("()=>[...document.querySelectorAll('.club-news .collection-card img')].every(i=>i.complete&&i.naturalWidth>0)")
        page.screenshot(path=str(OUT/f'desk-{width}.png'),full_page=True)
        check(not page.evaluate('document.documentElement.scrollWidth>innerWidth+1'),f'Desk fits {width}')
        for venue in ['salt','copper','nocturne','winter']:
            page.locator(f'[data-action="discover-collection"][data-value="{venue}"]').click()
            expect(page.locator('.collection-scope')).to_contain_text('Showing:')
            expect(page.locator('.puzzle-card')).to_have_count(24)
            check(page.locator('.filter-meta').inner_text().startswith('52 puzzles'),f'Invitation opens 52 {venue} puzzles at {width}')
            page.get_by_role('button',name='Show all collections',exact=True).click()
            expect(page.locator('.filter-meta')).to_contain_text(f'{OFFICIAL_COUNT} puzzles')
            page.locator('.footer [data-page="changelog"]').click()
            expect(page.locator('.release-entry')).to_have_count(len(RELEASES))
            page.get_by_role('button',name='Back to your desk',exact=True).click()
            expect(page.locator('.club-news')).to_be_visible()
        page.locator('.news-features [data-id="binary"]').click()
        expect(page.locator('.filter-meta')).to_contain_text(f'{BINARY_COUNT} puzzles')
        page.locator('.curation-collections > summary').click()
        page.locator('.collection-card[data-value="salt"]').click()
        expect(page.locator('.collection-card[data-value="salt"]')).to_have_attribute('aria-pressed','true')
        expect(page.locator('.filter-meta')).to_contain_text('4 puzzles')
        page.locator('.curation-collections').screenshot(path=str(OUT/f'collection-{width}.png'))
        page.get_by_role('button',name='Show all collections',exact=True).click()
        expect(page.locator('.filter-meta')).to_contain_text(f'{BINARY_COUNT} puzzles')
        page.locator('.footer [data-page="changelog"]').click()
        expect(page.get_by_role('heading',name='What’s new.')).to_be_visible()
        page.locator('[data-action="release-jump"][data-value="0.3.0"]').focus()
        page.keyboard.press('Enter')
        check(page.evaluate('document.activeElement.id')=='release-0.3.0',f'Keyboard history jump focuses historical version {width}')
        page.locator('[data-action="release-jump"][data-value="0.8.2"]').click()
        page.screenshot(path=str(OUT/f'history-{width}.png'),full_page=True)
        check(not page.evaluate('document.documentElement.scrollWidth>innerWidth+1'),f'History fits {width}')
        page.wait_for_function('()=>navigator.serviceWorker.controller && AlibiDiagnostics.getStatus().offlineReady')
        context.set_offline(True);page.reload()
        expect(page.locator('.release-entry')).to_have_count(len(RELEASES))
        check(True,f'All historical versions reload offline at {width}')
        context.set_offline(False)
        page.get_by_role('button',name='Back to your desk',exact=True).click()
        page.locator('.top-actions [data-page="settings"]').click()
        page.locator('#setting-largeText').check()
        page.locator('#setting-contrast').check()
        page.locator('[aria-label="Alibi home"]:visible').click()
        expect(page.locator('html')).to_have_attribute('data-large','true')
        page.locator('.club-news').scroll_into_view_if_needed()
        check(not page.evaluate('document.documentElement.scrollWidth>innerWidth+1'),f'Large-text discovery fits {width}')
        page.locator('.club-news').screenshot(path=str(OUT/f'large-discovery-{width}.png'))
        page.locator('.top-actions [data-page="settings"]').click()
        page.locator('#theme-select').select_option('night')
        page.locator('[aria-label="Alibi home"]:visible').click()
        page.locator('.club-news').screenshot(path=str(OUT/f'night-discovery-{width}.png'))
        check(not errors,f'No page errors at {width}')
        context.close()
    browser.close()
(OUT/'results.json').write_text(json.dumps({'passed':True,'checks':checks},indent=2))
print(f'{len(checks)} discovery/history checks passed')
