'use strict';
// Guards the pinned transitive patches in the package.json `overrides` map.
// Dependabot alert #15: uuid below 11.1.1 misses a buffer bounds check in
// v3/v5/v6 when the caller supplies `buf`. The vulnerable copy is reached via
// @capacitor/cli -> xcode, and upstream xcode is unmaintained, so the override
// pins uuid for the xcode subtree instead of waiting on a parent release.
const assert = require('node:assert/strict');
const path = require('node:path');
const uuid = require('uuid');

const xcodeDir = path.dirname(require.resolve('xcode'));
const xcodeUuidPackage = require.resolve('uuid/package.json', { paths: [xcodeDir] });
assert.equal(
  xcodeUuidPackage,
  require.resolve('uuid/package.json'),
  'xcode resolves to the single hoisted uuid copy',
);
const uuidVersion = require('uuid/package.json').version;
const [major, minor, patch] = uuidVersion.split('.').map(Number);
assert.ok(
  major > 11 || (major === 11 && (minor > 1 || (minor === 1 && patch >= 1))),
  `uuid is at or above the first patched release 11.1.1 (found ${uuidVersion})`,
);

// Behavioral proof the patch is present: undersized output buffers throw
// instead of silently truncating the generated bytes.
assert.throws(() => uuid.v3('alibi', uuid.v3.URL, Buffer.alloc(4)), RangeError);
assert.throws(() => uuid.v5('alibi', uuid.v5.URL, Buffer.alloc(4)), RangeError);
assert.throws(() => uuid.v6({}, Buffer.alloc(4)), RangeError);

// Compat guard: xcode is the only uuid consumer and only calls v4, so its
// project-ID generation must keep working across the major-version override.
const xcode = require('xcode');
const project = xcode.project('uuid-override-fixture.pbxproj');
project.hash = { project: { objects: {} } };
assert.match(project.generateUuid(), /^[0-9A-F]{24}$/);
