#!/usr/bin/env node
/* node replay_challenges.cjs <pure-quiet-engine-module> <club-engine-module> [report.json]
   Modules must expose classicMove/classicWon/classicInitial and warehouse/reversi/borough.
   Do not load a browser-only view module: use the repository's pure engine exports.
   This verifier never writes to the repository or accepts an untrusted saved state. */
'use strict';const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
if(!process.argv[2]||!process.argv[3]){console.error('Usage: node replay_challenges.cjs <quiet-engine-module> <club-engine-module> [report.json]');process.exit(2);}
const Q=require(path.resolve(process.argv[2])),E=require(path.resolve(process.argv[3])),B=path.resolve(__dirname,'../../content');
assert.equal(typeof Q.classicMove,'function','Need pure classic engine exports');assert(E.warehouse&&E.reversi&&E.borough,'Need club engine exports');
const load=name=>JSON.parse(fs.readFileSync(path.join(B,'challenges',name+'.json'),'utf8')).challenges;const report={classic:[],warehouse:[],reversi:[],borough:[]};
for(const c of load('classics')){let s=structuredClone(c.startState);for(const a of c.solutionActions){const before=structuredClone(s),r=Q.classicMove(s,a);assert(!r.error,c.id);assert.deepEqual(s,before,c.id+' mutated prior state');s=r.state;}assert(Q.classicWon(s),c.id);if(c.startActions){let t=Q.classicInitial(c.startState.id);for(const a of c.startActions){const r=Q.classicMove(t,a);assert(!r.error);t=r.state;}t.moves=0;assert.deepEqual(t,c.startState);}report.classic.push({id:c.id,winningReplay:true,immutable:true});}
for(const c of load('warehouse')){const index=E.warehouse.maps.length;E.warehouse.maps.push({name:c.title,subtitle:'Curation verification only',map:c.map});const start=E.warehouse.initial(index);let s=start;for(const m of c.solutionPath){const before=structuredClone(s),prior=s; s=E.warehouse.move(s,({U:'up',R:'right',D:'down',L:'left'})[m]);assert.deepEqual(prior,before,c.id+' mutated prior state');}assert(s.done,c.id);const result=E.warehouse.solve(start,250000);assert.equal(result.path.length,c.verification.minimumWalkingMoves,c.id);report.warehouse.push({id:c.id,winningReplay:true,shortestWalkingPath:c.verification.minimumWalkingMoves});}
function minimax(s,owner,memo){const key=s.board.join(',')+'/'+s.turn;if(memo.has(key))return memo.get(key);if(s.done){const score=E.reversi.score(s);return (score.gold-score.ink)*owner;}const values=E.reversi.legal(s).map(c=>minimax(E.reversi.move(s,c),owner,memo));assert(values.length,'Reducer must handle automatic passes');const value=s.turn===owner?Math.max(...values):Math.min(...values);memo.set(key,value);return value;}
for(const c of load('reversi')){let s=E.reversi.initial();for(const a of c.startActions){assert(E.reversi.legal(s).includes(a));s=E.reversi.move(s,a);}assert.deepEqual(s,c.startState,c.id);const memo=new Map(),values=E.reversi.legal(s).map(cell=>({cell,value:minimax(E.reversi.move(s,cell),s.turn,memo)}));assert.equal(values.filter(x=>x.value>0).length,1,c.id);assert.equal(values.find(x=>x.value>0).cell,c.solutionFirstMove);for(const v of c.rootMoveValues)assert.equal(values.find(x=>x.cell===v.cell).value,v.finalMarginForPlayerToMove);for(const a of c.principalVariation){assert(E.reversi.legal(s).includes(a));s=E.reversi.move(s,a);}assert(s.done);report.reversi.push({id:c.id,legalStartReplay:true,uniqueWinningMove:true,terminalMinimaxNodes:memo.size});}
for(const c of load('borough')){const s=E.borough.replay(c.seed,c.solutionActions);assert(s.done,c.id);const score=E.borough.score(s);assert.equal(score,c.referenceScore);assert(score>=c.targetScore);report.borough.push({id:c.id,referenceScore:score,targetScore:c.targetScore,optimalityClaim:false});}
report.allPassed=true;const text=JSON.stringify(report,null,2);if(process.argv[4])fs.writeFileSync(path.resolve(process.argv[4]),text+'\n');else console.log(text);console.log('59 challenge definitions reverified; this does not test their launcher/save adapters.');
