const fields = ["id","name","wing","family","mood","x","y","puzzle","line","gate"];
const rows = [
  ["gatehouse","The Gatehouse","The threshold","constraint","bronze",20,75,"gate","Rain has worked its way beneath the door. The keeper has left a lantern beside three brass wheels.","open"],
  ["library","The Long Library","The thinking wing","dossier","paper",37,50,"shelves","Someone has forced a maintenance slip between the wrong books. The shelf labels are still legible.","open"],
  ["observatory","The Observatory","The upper castle","binary","night",66,24,"clock","Finch kept the instruments here in better order than the station clock. His correction survives on a scrap of paper.","observatory"],
  ["cartography","The Map Room","The thinking wing","trail","blue",49,53,"route","A green footpath crosses the orchard. On the later survey, it stops at the edge of the paper.","cartography"],
  ["orangery","The Glass Orangery","The gardens","lightup","sage",72,68,"lamps","Three panes have been replaced. Beneath them, the lantern lattice is waiting for a steady hand.","open"],
  ["museum","The Museum of Questions","The Quiet Wing","history","paper",23,50,"museum","The drawers are shallow, the tables are worn, and you are allowed to touch almost everything.","open"],
  ["workshop","The Clockmaker’s Workshop","The working rooms","network","bronze",53,69,"hanoi","Finch used these three pegs to teach apprentices. The smallest disk has been mended twice.","open"],
  ["study","The Keeper’s Study","The thinking wing","witness","clay",47,39,"inference","The public report sits under glass. The working papers were put away in a cupboard without a label.","study"],
  ["west-stair","The Unrecorded Stair","Between rooms","meta","night",39,33,"reveal","The cabinet moves a few inches. There is a stair behind it, and a cold draught from the courtyard.","west"],
  ["conservatory","The Winter Conservatory","The Quiet Wing","rest","sage",81,75,"rest","There is a pencil in the guest book and enough light left to read by.","open"],
  ["portrait","The Portrait Gallery","The social rooms","picture","clay",61,46,null,"A strip of bare canvas runs along the lower edge. Someone changed their mind about who belonged in this picture.","planned"],
  ["dining","The Long Dining Room","The social rooms","scene","clay",55,59,null,"The guest list accounts for the places at the table. It says very little about the people carrying the plates.","planned"],
  ["court","The Court of Testimony","The social rooms","witness","paper",33,60,null,"Two witnesses described the same doorway by different names. Their accounts were filed as a contradiction.","planned"],
  ["music","The Music Salon","The social rooms","sequence","clay",65,57,null,"The music box stops at the same bar. A handwritten rest has been added to the score.","planned"],
  ["kitchen","The Old Kitchens","The working rooms","aquarium","bronze",46,77,null,"The measuring jugs are dented. Their marks disagree with the neat conversion chart beside the stove.","planned"],
  ["scullery","The Scullery","The working rooms","pouring","blue",56,80,null,"A pipe disappears behind the tiles. The drain plan gives it a different destination.","planned"],
  ["post","The Dead Letter Office","The working rooms","cipher","paper",31,72,null,"Four letters came back unopened. One was never posted.","planned"],
  ["archive","The Flooded Archive","Below the castle","dossier","blue",38,84,null,"The lowest shelf is empty. A brown line on the plaster explains where its contents went.","planned"],
  ["reservoir","The Cistern Vaults","Below the castle","aquarium","blue",61,86,null,"Each valve has two labels. The older set was scratched into the stone.","planned"],
  ["maze","The Yew Labyrinth","The gardens","trail","sage",84,53,null,"From the path, the hedges seem identical. The gardener used to draw the maze from an upstairs window.","planned"],
  ["orchard","The Old Orchard","The gardens","tents","sage",86,65,null,"The planting plan leaves a gap beside the oldest tree. There is no gap on the ground.","planned"],
  ["bridge","The Seven-Arch Bridge","Beyond the walls","bridges","blue",13,83,null,"Seven arches cross the river. The keeper suggests trying the model before attempting the walk.","planned"],
  ["boathouse","The Boathouse","Beyond the walls","crossing","blue",10,62,null,"A rescue list is pinned above the oars. Names were added in two different hands.","planned"],
  ["chapel","The Chapel of Echoes","The upper castle","logic","night",69,36,null,"An unsigned note has been left inside a book of readings. You may leave it unanswered.","planned"],
  ["sundial","The Sundial Court","The gardens","binary","bronze",72,81,null,"The noon mark is easy to find. The shadow beside it belongs to another hour.","planned"],
  ["nursery","The Paper Theatre","The upper castle","spatial","paper",57,31,null,"A paper stage folds into a box. One of its backdrops shows a doorway missing from the official plan.","planned"],
  ["rookery","The Rookery","The upper castle","network","night",79,29,null,"The message tubes follow an old delivery chart. One route depends on a single connection.","planned"],
  ["chess","The Knight’s Chamber","The thinking wing","knight","bronze",30,38,null,"A knight stands in the corner of an unfinished floorboard tour.","planned"],
  ["number","The Number Cabinet","The thinking wing","sudoku","paper",34,44,null,"The little drawers contain number tiles. Several labels have been replaced by relationships.","planned"],
  ["inequality","The Balancing Hall","The thinking wing","futoshiki","bronze",43,46,null,"The door weights have lost their numbers. The balances still work.","planned"],
  ["borough","The Model Village","The Quiet Wing","city","sage",19,65,null,"An architectural model occupies most of the table. The village beyond the window has grown differently.","planned"],
  ["hearth","The Companion Hearth","The Quiet Wing","pets","clay",24,59,null,"A cushion has been claimed beside the stove. Its occupant has left muddy prints on the visitor book.","planned"]
];
export default rows.map((row, index) => ({
  ...Object.fromEntries(fields.map((key, i) => [key, row[i]])),
  number: index + 1,
  implemented: row[9] !== 'planned',
}));
